install:
	npm install

serve:
	npm start

# se debe parametrizar para que esto se vaya directo a las carpetas respectivas
# por ahora se mueve a mano
# build_dev:
# 	rm -rf ../backend/_frontend/dev
# 	npm run build

# build_test:
# 	rm -rf ../backend/_frontend/test
# 	NODE_ENV=production npm run build

# build_prod:
# 	rm -rf ../backend/_frontend/prod
# 	VUE_APP_OUTPUT_DIR=../backend/_frontend/prod BASE_URL=https://epec.ing.uchile.cl/postulacion VUE_APP_BACKEND_URL=https://epec.ing.uchile.cl/postulacion/api VUE_APP_PUBLIC_PATH=/postulacion/ npm run build