#version: "3.4" 
 
services:
  db:
    image: postgres:12
    container_name: postgres-db
    environment: 
      POSTGRES_USER: museomapa_u
      POSTGRES_PASSWORD: AbareMuonegit-E13
      POSTGRES_DB: museomapa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    # ports:
    #   - "5433:5432"

  django:
    build: ./backend
    container_name: django-backend
    env_file: ./backend/catalogo_arqueologico/.env
    volumes:
      - ./backend:/app
      - ./data:/data
      - django_static:/app/static # This line ensures the statics files are stored in a volume
      - django_media:/app/media # This line ensures the media files are stored in a volume
    expose:
      - 8000
    depends_on:
      - db

  react:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
      - react_build:/app/build # This line ensures the static frontend files are stored in a volume
    expose:
      - 3000
    depends_on:
      - django

  nginx:
    build:
      context: ./nginx
    ports:
      - 3108:80
    depends_on:
      - django
      - react
    volumes:
      - django_static:/static # This line mounts the static files in Nginx
      - django_media:/media # This line mounts the media files in Nginx
      - react_build:/react # This line mounts the static files in Nginx

volumes:
  postgres_data:
  django_media:
  django_static:
  react_build:
