# Generated by Django 3.2.25 on 2024-11-05 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownloadingRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(max_length=500, null=True)),
                ('admin_comments', models.TextField(max_length=500, null=True)),
                ('is_registered', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_requester', to='piezas.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partiallyaccepted', 'Partially accepted'), ('downloaded', 'Downloaded')], default='pending', max_length=17)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='piezas.artifact')),
                ('artifact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='piezas.bulkdownloadingrequest')),
            ],
        ),
    ]
