# Generated by Django 3.2.25 on 2024-11-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_bulkdownloadingrequest_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdownloadingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partiallyaccepted', 'Partially accepted'), ('downloaded', 'Downloaded')], default='pending', max_length=17),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
