# Generated by Django 3.2.25 on 2024-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_image_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='descriptor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='descriptor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
