services:
    django:
        networks:
            - nginx-proxy
        container_name: catalogo-piezas-arqueologicas
        hostname: catalogo-piezas-arqueologicas.apps.dcc.uchile.cl
        build: 
            context: ../
            dockerfile: .docker/backend/Dockerfile
            target: production
            args:
                UID: 1001
                GID: 100
        command: gunicorn --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir /dev/shm --bind :8000 backend.wsgi
        volumes:
            - /home/instalar/static/catalogo-piezas-arqueologicas/:/static/:rw
            - /home/instalar/media/catalogo-piezas-arqueologicas/:/media/:rw
            - /home/instalar/logs/catalogo-piezas-arqueologicas:/logs:rw
            - /home/instalar/backup/catalogo-piezas-arqueologicas:/backup:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        expose:
            - 8000
        env_file:
            - backend/.env
        restart: always

networks:
    nginx-proxy:
      external: true
      name: nginx-proxy