services:
    postgresql:
        image: postgres:13.3
        container_name: postgresql
        expose:
            - 5432
        restart: unless-stopped
        volumes:
            - ./data/postgres/:/var/lib/postgresql:rw
        environment: 
            POSTGRES_USER: desarrollo
            POSTGRES_PASSWORD: desarroll0
            POSTGRES_DB: catalogo-piezas-arqueologicas
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U desarrollo -d catalogo-piezas-arqueologicas"]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        build: 
            context: ../
            dockerfile: .docker/backend/Dockerfile
            target: develop
        container_name: catalogo-piezas-arqueologicas
        command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000 --settings=backend.settings.docker --nothreading"]
        restart: always
        volumes:
            - ../backend/:/app/:cached
            - ../backend/_media/:/media/:cached
            # - ../backend/staticfiles/:/static/:cached
            - ./data/logs:/logs:cached
            - ../docs/:/docs/:cached
        ports: 
            - 8000:8000
        env_file: ./backend/.env
        depends_on:
            postgresql:
                condition: service_healthy